name: employee-payroll

services:
  - name: payroll-backend
    github:
      repo: SanthoshkumarSelvakumar/employee-management
      branch: main
      deploy_on_push: true
    source_dir: /payroll-backend
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db.PORT}
      - key: DB_NAME
        scope: RUN_TIME
        value: ${db.DATABASE}
      - key: DB_USERNAME
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${db.PASSWORD}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: REPLACE_WITH_STRONG_SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}

  - name: payroll-frontend
    github:
      repo: SanthoshkumarSelvakumar/employee-management
      branch: main
      deploy_on_push: true
    source_dir: /payroll-frontend
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
